/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppLocalProjectsIndexRouteImport } from './routes/_app/local-projects/index'
import { Route as AppSettingsReposRouteImport } from './routes/_app/settings/repos'
import { Route as AppSettingsProjectsRouteImport } from './routes/_app/settings/projects'
import { Route as AppSettingsMcpRouteImport } from './routes/_app/settings/mcp'
import { Route as AppSettingsGeneralRouteImport } from './routes/_app/settings/general'
import { Route as AppSettingsAgentsRouteImport } from './routes/_app/settings/agents'
import { Route as AppLocalProjectsProjectIdIndexRouteImport } from './routes/_app/local-projects/$projectId/index'
import { Route as AppLocalProjectsProjectIdTasksIndexRouteImport } from './routes/_app/local-projects/$projectId/tasks/index'
import { Route as AppLocalProjectsProjectIdTasksTaskIdIndexRouteImport } from './routes/_app/local-projects/$projectId/tasks/$taskId/index'
import { Route as LocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdFullRouteImport } from './routes/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/full'
import { Route as AppLocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdIndexRouteImport } from './routes/_app/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppLocalProjectsIndexRoute = AppLocalProjectsIndexRouteImport.update({
  id: '/local-projects/',
  path: '/local-projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsReposRoute = AppSettingsReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProjectsRoute = AppSettingsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsMcpRoute = AppSettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAgentsRoute = AppSettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppLocalProjectsProjectIdIndexRoute =
  AppLocalProjectsProjectIdIndexRouteImport.update({
    id: '/local-projects/$projectId/',
    path: '/local-projects/$projectId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppLocalProjectsProjectIdTasksIndexRoute =
  AppLocalProjectsProjectIdTasksIndexRouteImport.update({
    id: '/local-projects/$projectId/tasks/',
    path: '/local-projects/$projectId/tasks/',
    getParentRoute: () => AppRoute,
  } as any)
const AppLocalProjectsProjectIdTasksTaskIdIndexRoute =
  AppLocalProjectsProjectIdTasksTaskIdIndexRouteImport.update({
    id: '/local-projects/$projectId/tasks/$taskId/',
    path: '/local-projects/$projectId/tasks/$taskId/',
    getParentRoute: () => AppRoute,
  } as any)
const LocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdFullRoute =
  LocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdFullRouteImport.update({
    id: '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/full',
    path: '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/full',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppLocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdIndexRoute =
  AppLocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdIndexRouteImport.update({
    id: '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/',
    path: '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/settings/agents': typeof AppSettingsAgentsRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/mcp': typeof AppSettingsMcpRoute
  '/settings/projects': typeof AppSettingsProjectsRoute
  '/settings/repos': typeof AppSettingsReposRoute
  '/local-projects/': typeof AppLocalProjectsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/local-projects/$projectId/': typeof AppLocalProjectsProjectIdIndexRoute
  '/local-projects/$projectId/tasks/': typeof AppLocalProjectsProjectIdTasksIndexRoute
  '/local-projects/$projectId/tasks/$taskId/': typeof AppLocalProjectsProjectIdTasksTaskIdIndexRoute
  '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/full': typeof LocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdFullRoute
  '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/': typeof AppLocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/settings/agents': typeof AppSettingsAgentsRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/settings/mcp': typeof AppSettingsMcpRoute
  '/settings/projects': typeof AppSettingsProjectsRoute
  '/settings/repos': typeof AppSettingsReposRoute
  '/local-projects': typeof AppLocalProjectsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/local-projects/$projectId': typeof AppLocalProjectsProjectIdIndexRoute
  '/local-projects/$projectId/tasks': typeof AppLocalProjectsProjectIdTasksIndexRoute
  '/local-projects/$projectId/tasks/$taskId': typeof AppLocalProjectsProjectIdTasksTaskIdIndexRoute
  '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/full': typeof LocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdFullRoute
  '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId': typeof AppLocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/settings/agents': typeof AppSettingsAgentsRoute
  '/_app/settings/general': typeof AppSettingsGeneralRoute
  '/_app/settings/mcp': typeof AppSettingsMcpRoute
  '/_app/settings/projects': typeof AppSettingsProjectsRoute
  '/_app/settings/repos': typeof AppSettingsReposRoute
  '/_app/local-projects/': typeof AppLocalProjectsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/local-projects/$projectId/': typeof AppLocalProjectsProjectIdIndexRoute
  '/_app/local-projects/$projectId/tasks/': typeof AppLocalProjectsProjectIdTasksIndexRoute
  '/_app/local-projects/$projectId/tasks/$taskId/': typeof AppLocalProjectsProjectIdTasksTaskIdIndexRoute
  '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/full': typeof LocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdFullRoute
  '/_app/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/': typeof AppLocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/agents'
    | '/settings/general'
    | '/settings/mcp'
    | '/settings/projects'
    | '/settings/repos'
    | '/local-projects/'
    | '/settings/'
    | '/local-projects/$projectId/'
    | '/local-projects/$projectId/tasks/'
    | '/local-projects/$projectId/tasks/$taskId/'
    | '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/full'
    | '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/agents'
    | '/settings/general'
    | '/settings/mcp'
    | '/settings/projects'
    | '/settings/repos'
    | '/local-projects'
    | '/settings'
    | '/local-projects/$projectId'
    | '/local-projects/$projectId/tasks'
    | '/local-projects/$projectId/tasks/$taskId'
    | '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/full'
    | '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/settings'
    | '/_app/'
    | '/_app/settings/agents'
    | '/_app/settings/general'
    | '/_app/settings/mcp'
    | '/_app/settings/projects'
    | '/_app/settings/repos'
    | '/_app/local-projects/'
    | '/_app/settings/'
    | '/_app/local-projects/$projectId/'
    | '/_app/local-projects/$projectId/tasks/'
    | '/_app/local-projects/$projectId/tasks/$taskId/'
    | '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/full'
    | '/_app/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdFullRoute: typeof LocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdFullRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/local-projects/': {
      id: '/_app/local-projects/'
      path: '/local-projects'
      fullPath: '/local-projects/'
      preLoaderRoute: typeof AppLocalProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/repos': {
      id: '/_app/settings/repos'
      path: '/repos'
      fullPath: '/settings/repos'
      preLoaderRoute: typeof AppSettingsReposRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/projects': {
      id: '/_app/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof AppSettingsProjectsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/mcp': {
      id: '/_app/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof AppSettingsMcpRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/general': {
      id: '/_app/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AppSettingsGeneralRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/agents': {
      id: '/_app/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof AppSettingsAgentsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/local-projects/$projectId/': {
      id: '/_app/local-projects/$projectId/'
      path: '/local-projects/$projectId'
      fullPath: '/local-projects/$projectId/'
      preLoaderRoute: typeof AppLocalProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/local-projects/$projectId/tasks/': {
      id: '/_app/local-projects/$projectId/tasks/'
      path: '/local-projects/$projectId/tasks'
      fullPath: '/local-projects/$projectId/tasks/'
      preLoaderRoute: typeof AppLocalProjectsProjectIdTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/local-projects/$projectId/tasks/$taskId/': {
      id: '/_app/local-projects/$projectId/tasks/$taskId/'
      path: '/local-projects/$projectId/tasks/$taskId'
      fullPath: '/local-projects/$projectId/tasks/$taskId/'
      preLoaderRoute: typeof AppLocalProjectsProjectIdTasksTaskIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/full': {
      id: '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/full'
      path: '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/full'
      fullPath: '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/full'
      preLoaderRoute: typeof LocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdFullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/': {
      id: '/_app/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/'
      path: '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId'
      fullPath: '/local-projects/$projectId/tasks/$taskId/attempts/$attemptId/'
      preLoaderRoute: typeof AppLocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAgentsRoute: typeof AppSettingsAgentsRoute
  AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute
  AppSettingsMcpRoute: typeof AppSettingsMcpRoute
  AppSettingsProjectsRoute: typeof AppSettingsProjectsRoute
  AppSettingsReposRoute: typeof AppSettingsReposRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAgentsRoute: AppSettingsAgentsRoute,
  AppSettingsGeneralRoute: AppSettingsGeneralRoute,
  AppSettingsMcpRoute: AppSettingsMcpRoute,
  AppSettingsProjectsRoute: AppSettingsProjectsRoute,
  AppSettingsReposRoute: AppSettingsReposRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppLocalProjectsIndexRoute: typeof AppLocalProjectsIndexRoute
  AppLocalProjectsProjectIdIndexRoute: typeof AppLocalProjectsProjectIdIndexRoute
  AppLocalProjectsProjectIdTasksIndexRoute: typeof AppLocalProjectsProjectIdTasksIndexRoute
  AppLocalProjectsProjectIdTasksTaskIdIndexRoute: typeof AppLocalProjectsProjectIdTasksTaskIdIndexRoute
  AppLocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdIndexRoute: typeof AppLocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppLocalProjectsIndexRoute: AppLocalProjectsIndexRoute,
  AppLocalProjectsProjectIdIndexRoute: AppLocalProjectsProjectIdIndexRoute,
  AppLocalProjectsProjectIdTasksIndexRoute:
    AppLocalProjectsProjectIdTasksIndexRoute,
  AppLocalProjectsProjectIdTasksTaskIdIndexRoute:
    AppLocalProjectsProjectIdTasksTaskIdIndexRoute,
  AppLocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdIndexRoute:
    AppLocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdFullRoute:
    LocalProjectsProjectIdTasksTaskIdAttemptsAttemptIdFullRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
